FROM python:3.11-slim
WORKDIR /app
RUN pip install poetry --no-cache-dir
COPY pyproject.toml ./
RUN poetry config virtualenvs.create false && poetry install --no-root --no-interaction
COPY api ./api
EXPOSE 8200
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8200"]
